### ISSUE TITLE
Fehler die noch behoben werden müssen/Sachen die noch gemacht werden müssten

### ISSUE THREAD

**Issue by EaMSo** [EaMSo/TUBAF-Planer#34]
- [x] ungerade/grade Woche bei Wochenplan und
- [x]  Zeit am Rand
- [x] Ladekringel/Balken wenn Module geladen werden (nicht soo wichtig)
- [x] #39
- [x] tutorial anleitung schreiben
- [x] pfad zu datenbank bei button dücken ausgeben
- [x] #40
- [x] Clear Button
- [x] wenn Hinzufügen oder Custom Modul erstellen gedrückt wird bevor irgendetwas anders gedrückt wir gibt es eine Fehlermeldung
- [x] Modul Detail Page schöner machen
- [ ] Publishen
- [x] UML-Diagramm erneuern
- [ ] Noch einen Test?

**Comment by EinJannik** [comment]
Weitere Tests fallen mir gerade nicht ein

**Comment by EinJannik** [comment]
Publishen würde ich erst machen, wenn weitere Features implementiert sind (schnellerer DB Zugriff)
