### ISSUE TITLE
UI in Arbeit, weiteres Vorgehen

### ISSUE THREAD

**Issue by EinJannik** [EaMSo/TUBAF-Planer#4]
Wie abgesprochen arbeite ich gerade an einem UI mit MAUI. Ich benötige Zugriff auf die Felder der Modulklasse um diese Anzeigen zu können. Bitte implementiere dies zeitnah. 💢 
Außerdem müssen wir noch schauen, wie man das Projekt dann hier hinzufügt. Dafür machen wir ein Meeting um das zu besprechen.🤓

**Comment by EaMSo** [comment]
Ok ich setzt mich dran sollte bald fertig sein! 👍

**Comment by EaMSo** [comment]
## Weiteres Vorgehen was aus unserem Meeting hervorgeht:
### Was noch gemacht werden muss:
- FullModuleList erstellen (gibt liste von allen Modulinstanzen aus) (Emil)
- Planbuilder programmieren (Emil+Jannik) 
-> UI fertigstellen (Jannik)
- CustomModule erstellen (?)

### Danach:
- ModulList -> gibt liste Relevant für Studiengang aus (?)
- Vorsortierung Implementieren (?)

👍

**Comment by EaMSo** [comment]
### Jetziger Stand:
- FullModuleList erstellen (gibt liste von allen Modulinstanzen aus) (Emil) ✔️
- Planbuilder programmieren (Emil+Jannik) 2/3 ✔️
-> UI fertigstellen (Jannik) 3/4 ✔️
- CustomModule erstellen (Emil+Jannik)✔️

### Danach:
- ModulList -> gibt liste Relevant für Studiengang aus (?) ⭕
- Vorsortierung Implementieren (?) ⭕
